[package]
name = "parcel"
version = "1.8.0"
authors = ["Nate Catelli <ncatelli@packetfire.org>"]
edition = "2018"
publish = false

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "text_parsing"
harness = false

[[bench]]
name = "binary_parsing"
harness = false

[dependencies]
