name: Test

on: 
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run run benchmarks
      uses: actions-rs/cargo@v1
      with:
        command: bench
  flamegraph:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bench: 
          - "text_parsing"
          - "binary_parsing"
    steps:
      - uses: actions/checkout@master
      - name: Set kernel profiling sysctls
        run: echo "2" > /proc/sys/kernel/perf_event_paranoid
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Add cargo-flamegraph
        run: cargo install flamegraph 
      - name: Generate benchmark flamegraphs
        run: cargo flamegraph --bench ${{ matrix.bench }} -- --bench
      - name: Upload rendered graphs
        uses: actions/upload-artifact@v2
        with:
          name: rendered-benchmark-flamegraphs
          path: "*.svg"
